server:
  port: 8080

camel:
  springboot:
    # The Camel context name
    name: ServicesRest

main:
  api:
    path: 

# Binding health checks to a different port
# management:
#   port: 8081

# disable all management enpoints except health
management:
  endpoint:
    camelroutes:
      enabled: true
# endpoints:
#   enabled: false
#   health:
#     enabled: true

# The application configuration properties
# quickstart:
#   generateOrderPeriod: 10s
#   processOrderPeriod: 30s